# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ee2492d5328e43d02d1e67054a8985b19b8c33df30a0ecff1fd54dcc7ae02381e4d9c955b35bc079c40860127e8ec9aa3474ffebe66a916366821e7ead75800

test:
  secret_key_base: c81786e53ca406ee58d666c35a7a94045869e0e28635c4d2109d2aebdaeae35c09d672dbebe409aa46b6bf73898c250a6a8c933b8e154e2ec52e1e1bdaa70205

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
